In [1]:
import pandas as pd
import numpy as np
import nltk
import re
from nltk.corpus import stopwords

In [2]:
df = pd.read_csv('fake_news_train.csv')

df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [3]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [4]:
df = df.dropna()

In [5]:
df.shape

(18285, 5)

In [6]:
df = df.reset_index()
df.head()

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   

               author                                               text  \
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...   
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...   
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...   
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...   
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...   

   label  
0      1  
1      0  
2      1  
3      1  
4      1

In [7]:
df = df.drop(['index','id'], axis = 1)
df.head()

title              author  \
0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [8]:
x = df.drop('label', axis =1)

y = df['label']

In [9]:
x.shape

(18285, 3)

In [10]:
y.shape

(18285,)

In [11]:
message = x.copy()

message

title  \
0      House Dem Aide: We Didn’t Even See Comey’s Let...   
1      FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2                      Why the Truth Might Get You Fired   
3      15 Civilians Killed In Single US Airstrike Hav...   
4      Iranian woman jailed for fictional unpublished...   
...                                                  ...   
18280  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  Macy’s Is Said to Receive Takeover Approach by...   
18283  NATO, Russia To Hold Parallel Exercises In Bal...   
18284                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 3 columns]

In [12]:
from tensorflow.keras.layers import Embedding                            ## embedding layer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot      ## one hot encoding

from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [13]:
from nltk.stem.porter import PorterStemmer

stemmer = PorterStemmer()

In [14]:
corpus = []

for i in range(0, len(message)):
    
    review = re.sub('[^a-zA-Z]',' ', message['title'][i])
    
    review = review.lower()
    
    review = review.split()
    
    review = [stemmer.stem(word) for word in review if word not in stopwords.words('english')]
    
    review = ' '.join(review)
    
    corpus.append(review)

In [15]:
corpus[6]

'beno hamon win french socialist parti presidenti nomin new york time'

In [16]:
### Vocabulary size
voc_size=5000

In [17]:
onehot_repre = [one_hot(words, voc_size) for words in corpus]

onehot_repre

[[3329, 4034, 896, 75, 2661, 15, 854, 2345, 3506, 4014],
 [3170, 1697, 590, 1211, 2799, 4235, 504],
 [3670, 3852, 266, 711],
 [4999, 2929, 3964, 4527, 3776, 2474],
 [2543, 2799, 3595, 1543, 4100, 1758, 2799, 207, 1297, 1580],
 [89,
  4896,
  1747,
  1233,
  157,
  3304,
  2055,
  4455,
  2117,
  2500,
  3841,
  291,
  3755,
  3802,
  504],
 [2289, 3165, 2929, 1032, 4686, 691, 1783, 1350, 2213, 91, 649],
 [1216, 28, 4293, 2944, 4668, 2049, 3304, 1592, 2213, 91, 649],
 [3158, 3589, 4683, 1642, 997, 1399, 3397, 1050, 3304, 2385],
 [261, 1909, 1396, 227, 1910, 961, 2532, 4895],
 [2796, 4661, 4421, 4022, 3563, 1406, 1429, 1617, 4180, 1381, 3873],
 [4527, 3168, 2661, 1399, 3304, 4668],
 [2547, 505, 4652, 145, 3221, 4867, 3829, 1587, 2854],
 [2510, 4042, 2430, 4198, 4418, 2599, 108, 2213, 91, 649],
 [2167, 4942, 4157, 3295, 2991, 2213, 91, 649],
 [2856, 4700, 2187, 1823, 778, 2487, 141, 960, 3688, 728],
 [3794, 954, 1697],
 [1276, 4201, 1303, 4873, 3304, 4509, 767, 504],
 [3305, 4254, 590, 33

# Embedding Representation

In [18]:
sent_length = 20              

embedded_docs = pad_sequences(onehot_repre, padding= 'pre', maxlen = sent_length)     
                                     
print(embedded_docs)

[[   0    0    0 ... 2345 3506 4014]
 [   0    0    0 ... 2799 4235  504]
 [   0    0    0 ... 3852  266  711]
 ...
 [   0    0    0 ... 2213   91  649]
 [   0    0    0 ... 3657 3441 3812]
 [   0    0    0 ... 1328 3878 2728]]


## model 1........ LSTM model

In [19]:
embedding_vector_features = 40

model = Sequential()

model.add(Embedding(voc_size, embedding_vector_features, input_length= sent_length))

model.add(LSTM(100)) 

model.add(Dense(1, activation= 'sigmoid'))     

In [20]:
model.compile( loss= 'binary_crossentropy', optimizer ='adam', metrics= ['accuracy'])

print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


# model 2 ..... Bidirectional LSTM

In [21]:
embedding_vector_features = 40

model_2 = Sequential()

model_2.add(Embedding(voc_size, embedding_vector_features, input_length= sent_length))

model_2.add(Bidirectional(LSTM(100)))  

model_2.add(Dropout(0.3))

model_2.add(Dense(1, activation= 'sigmoid'))   

In [23]:
model_2.compile(loss ='binary_crossentropy', optimizer ='adam', metrics =['accuracy'])

print(model_2.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 bidirectional (Bidirectiona  (None, 200)              112800    
 l)                                                              
                                                                 
 dropout (Dropout)           (None, 200)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 201       
                                                                 
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [24]:
len(embedded_docs)

18285

In [30]:
embedded_docs.shape

(18285, 20)

In [26]:
y.shape

(18285,)

In [27]:
## convert the embedded documents to an arry

x_final = np.array(embedded_docs)

y_final = np.array(y)

In [28]:
x_final

array([[   0,    0,    0, ..., 2345, 3506, 4014],
       [   0,    0,    0, ..., 2799, 4235,  504],
       [   0,    0,    0, ..., 3852,  266,  711],
       ...,
       [   0,    0,    0, ..., 2213,   91,  649],
       [   0,    0,    0, ..., 3657, 3441, 3812],
       [   0,    0,    0, ..., 1328, 3878, 2728]])

In [29]:
x_final.shape

(18285, 20)

In [32]:
y_final.shape

(18285,)

In [33]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_final, y_final, random_state= 0, test_size= 0.33)

In [34]:
model.fit(x_train, y_train, validation_data= (x_test, y_test), epochs= 10, batch_size =64)

Epoch 1/10
192/192 [==============================] - 15s 37ms/step - loss: 0.3329 - accuracy: 0.8413 - val_loss: 0.1912 - val_accuracy: 0.9135
Epoch 2/10
192/192 [==============================] - 6s 31ms/step - loss: 0.1420 - accuracy: 0.9451 - val_loss: 0.1933 - val_accuracy: 0.9142
Epoch 3/10
192/192 [==============================] - 6s 33ms/step - loss: 0.1030 - accuracy: 0.9642 - val_loss: 0.2119 - val_accuracy: 0.9118
Epoch 4/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0806 - accuracy: 0.9730 - val_loss: 0.2373 - val_accuracy: 0.9107
Epoch 5/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0633 - accuracy: 0.9793 - val_loss: 0.2923 - val_accuracy: 0.9157
Epoch 6/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0507 - accuracy: 0.9842 - val_loss: 0.2848 - val_accuracy: 0.9153
Epoch 7/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0389 - accuracy: 0.9886 - val_loss: 0.3420 - val_accuracy: 0.916

In [35]:
y_pred = model.predict(x_test)

189/189 [==============================] - 2s 8ms/step


In [36]:
pred2 = (y_pred > 0.5).astype("int32")

In [37]:
pred2

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [1]])

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [40]:
confusion_matrix(y_test, pred2)

array([[3123,  266],
       [ 285, 2361]], dtype=int64)

In [41]:
accuracy_score(y_test, pred2)

0.9086992543496272

In [44]:
print(classification_report(y_test, pred2))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      3389
           1       0.90      0.89      0.90      2646

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035

