In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('fake_news_train.csv')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [5]:
df.shape

(20800, 5)

In [6]:
df = df.dropna()

In [7]:
df.shape

(18285, 5)

In [8]:
x = df.drop(['label'], axis= 1)
x.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [9]:
y = df['label']
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [10]:
message = df.copy()

message.shape

(18285, 5)

In [11]:
message.reset_index(inplace= True)
message.head()

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   

               author                                               text  \
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...   
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...   
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...   
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...   
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...   

   label  
0      1  
1      0  
2      1  
3      1  
4      1

In [12]:
message['title'][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [13]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [14]:
stemmer = PorterStemmer()

In [15]:
corpus =[]

for i in range(0, len(message)):
    
    review = re.sub('[^a-zA-Z]',' ',message['title'][i])
    
    review = review.lower()
    
    review = review.split()
    
    review = [stemmer.stem(word) for word in review if word not in set(stopwords.words('english'))]
    
    review = ' '.join(review)
    
    corpus.append(review)

In [16]:
corpus[3]

'civilian kill singl us airstrik identifi'

# Onehot Representation

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [18]:
## set the vocabulary size
voc_size = 5000

In [19]:
onehot_repre = [one_hot(word, voc_size) for word in corpus]

onehot_repre

[[1684, 2289, 2164, 2411, 3163, 1747, 3584, 4507, 1335, 1985],
 [102, 2641, 810, 1382, 1047, 3654, 3215],
 [3645, 3226, 2216, 4469],
 [3400, 3498, 4901, 4146, 4949, 2238],
 [1756, 1047, 1464, 2942, 780, 4236, 1047, 1895, 3100, 4390],
 [1659,
  2381,
  4437,
  2059,
  3591,
  1148,
  1189,
  3196,
  4091,
  3276,
  1590,
  2185,
  1708,
  3949,
  3215],
 [2654, 3015, 1918, 3505, 4057, 2882, 3712, 4399, 1562, 326, 2648],
 [3239, 236, 2803, 1708, 949, 4669, 1148, 1628, 1562, 326, 2648],
 [2177, 79, 722, 236, 4282, 3512, 4572, 2696, 1148, 4240],
 [4301, 732, 1685, 1280, 4193, 1487, 4827, 2220],
 [3786, 3984, 606, 1464, 1723, 1848, 2744, 3811, 775, 3506, 3748],
 [4146, 2994, 3163, 3512, 1148, 949],
 [1172, 3805, 1704, 3938, 2601, 3304, 3968, 4524, 4882],
 [1052, 1500, 323, 4910, 898, 3173, 436, 1562, 326, 2648],
 [948, 1105, 422, 3341, 3097, 1562, 326, 2648],
 [3286, 564, 4439, 1237, 3605, 2120, 4097, 3335, 4306, 1454],
 [3770, 451, 2641],
 [2817, 4119, 3717, 3488, 1148, 4207, 4273, 3215],


# Embedding Representation

In [20]:
sent_length = 20

embedded_docs = pad_sequences(onehot_repre, padding= 'pre', maxlen = sent_length)

embedded_docs

array([[   0,    0,    0, ..., 4507, 1335, 1985],
       [   0,    0,    0, ..., 1047, 3654, 3215],
       [   0,    0,    0, ..., 3226, 2216, 4469],
       ...,
       [   0,    0,    0, ..., 1562,  326, 2648],
       [   0,    0,    0, ...,  963, 3177, 4178],
       [   0,    0,    0, ..., 3302, 2220, 1971]])

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1684,
       2289, 2164, 2411, 3163, 1747, 3584, 4507, 1335, 1985])

# creating model

In [22]:
embedding_vector_features = 40

model =Sequential()

model.add(Embedding( voc_size, embedding_vector_features, input_length= sent_length))

model.add(LSTM(100))

model.add(Dense(1 , activation= 'sigmoid'))

model.compile( loss= 'binary_crossentropy', optimizer = 'adam', metrics= ['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [23]:
len(embedded_docs)

18285

In [24]:
y.shape

(18285,)

In [25]:
import numpy as np

x_final = np.array(embedded_docs)
y_final = np.array(y)

In [26]:
x_final.shape

(18285, 20)

In [27]:
x.shape

(18285, 4)

In [28]:
y_final.shape

(18285,)

In [29]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_final, y_final, random_state= 0, test_size= 0.33)

# Model Training

In [30]:
model.fit(x_train, y_train, validation_data= (x_test, y_test), epochs= 10, batch_size = 65)

Epoch 1/10
189/189 [==============================] - 14s 40ms/step - loss: 0.3379 - accuracy: 0.8353 - val_loss: 0.1934 - val_accuracy: 0.9162
Epoch 2/10
189/189 [==============================] - 6s 33ms/step - loss: 0.1366 - accuracy: 0.9477 - val_loss: 0.1923 - val_accuracy: 0.9200
Epoch 3/10
189/189 [==============================] - 6s 32ms/step - loss: 0.0990 - accuracy: 0.9631 - val_loss: 0.2157 - val_accuracy: 0.9109
Epoch 4/10
189/189 [==============================] - 6s 33ms/step - loss: 0.0662 - accuracy: 0.9788 - val_loss: 0.2443 - val_accuracy: 0.9100
Epoch 5/10
189/189 [==============================] - 6s 33ms/step - loss: 0.0437 - accuracy: 0.9869 - val_loss: 0.3013 - val_accuracy: 0.9082
Epoch 6/10
189/189 [==============================] - 6s 33ms/step - loss: 0.0254 - accuracy: 0.9917 - val_loss: 0.4264 - val_accuracy: 0.9069
Epoch 7/10
189/189 [==============================] - 6s 33ms/step - loss: 0.0204 - accuracy: 0.9944 - val_loss: 0.4092 - val_accuracy: 0.906

# Performance Metrics And Accuracy

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [33]:
y_pred = model.predict(x_test)

189/189 [==============================] - 2s 8ms/step


### Prediction_1 (how to predict the class)

In [34]:
classes_x=np.argmax(y_pred,axis=1)

In [35]:
classes_x

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [36]:
confusion_matrix(y_test, classes_x)

array([[3389,    0],
       [2646,    0]], dtype=int64)

In [37]:
accuracy_score(y_test, classes_x)

0.5615575807787904

### Prediction_2 (how to predict the class)

In [38]:
pred2 = (y_pred > 0.5).astype("int32")

In [39]:
pred2

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [1]])

In [40]:
confusion_matrix(y_test, pred2)

array([[3138,  251],
       [ 314, 2332]], dtype=int64)

In [41]:
accuracy_score(y_test, pred2)

0.9063794531897266

# Adding Dropout

In [42]:
from tensorflow.keras.layers import Dropout

In [43]:
embedding_vector_features = 40

model =Sequential()

model.add(Embedding( voc_size, embedding_vector_features, input_length= sent_length))

model.add(Dropout(0.3))

model.add(LSTM(100))

model.add(Dropout(0.3))

model.add(Dense(1 , activation= 'sigmoid'))

model.compile( loss= 'binary_crossentropy', optimizer = 'adam', metrics= ['accuracy'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 dropout (Dropout)           (None, 20, 40)            0         
                                                                 
 lstm_1 (LSTM)               (None, 100)               56400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [44]:
import numpy as np

x_final = np.array(embedded_docs)
y_final = np.array(y)

In [45]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_final, y_final, random_state= 0, test_size= 0.33)

In [46]:
model.fit(x_train, y_train, validation_data= (x_test, y_test), epochs= 10, batch_size = 65)

Epoch 1/10
189/189 [==============================] - 13s 44ms/step - loss: 0.3487 - accuracy: 0.8299 - val_loss: 0.1954 - val_accuracy: 0.9150
Epoch 2/10
189/189 [==============================] - 7s 37ms/step - loss: 0.1478 - accuracy: 0.9407 - val_loss: 0.1890 - val_accuracy: 0.9238
Epoch 3/10
189/189 [==============================] - 7s 39ms/step - loss: 0.1084 - accuracy: 0.9598 - val_loss: 0.2027 - val_accuracy: 0.9181
Epoch 4/10
189/189 [==============================] - 7s 36ms/step - loss: 0.0822 - accuracy: 0.9711 - val_loss: 0.2346 - val_accuracy: 0.9163
Epoch 5/10
189/189 [==============================] - 7s 37ms/step - loss: 0.0629 - accuracy: 0.9783 - val_loss: 0.2761 - val_accuracy: 0.9128
Epoch 6/10
189/189 [==============================] - 7s 39ms/step - loss: 0.0477 - accuracy: 0.9828 - val_loss: 0.2659 - val_accuracy: 0.9145
Epoch 7/10
189/189 [==============================] - 7s 36ms/step - loss: 0.0370 - accuracy: 0.9880 - val_loss: 0.3144 - val_accuracy: 0.916

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [48]:
y_pred = model.predict(x_test)

189/189 [==============================] - 2s 8ms/step


In [49]:
pred1 = (y_pred > 0.5).astype("int32")

In [50]:
confusion_matrix(y_test, pred1)

array([[3116,  273],
       [ 255, 2391]], dtype=int64)

In [51]:
accuracy_score(y_test, pred1)

0.9125103562551782