# One_hot_encoding

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sentences = ['i am jitesh sahu', 'i am a mechanical engineering student', 'i belong from bargarh', 
             'i am a fresher', 'playing badminton is my hobby', 'there is a long way to go']

In [3]:
## vocabulary size = 10000
voc_size = 10000

# One Hot Representation

In [4]:
onehot_repre = [one_hot(word, voc_size) for word in sentences]

print(onehot_repre)

[[7756, 7949, 6485, 9567], [7756, 7949, 1086, 9834, 2412, 483], [7756, 12, 1323, 8800], [7756, 7949, 1086, 399], [9092, 7374, 8916, 4438, 5808], [993, 8916, 1086, 7615, 4526, 8098, 8419]]


# Word Embedding Represntation

In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
sent_length = 10
embedded_docs = pad_sequences(onehot_repre, padding='pre', maxlen = sent_length) 

print(embedded_docs)                              

[[   0    0    0    0    0    0 7756 7949 6485 9567]
 [   0    0    0    0 7756 7949 1086 9834 2412  483]
 [   0    0    0    0    0    0 7756   12 1323 8800]
 [   0    0    0    0    0    0 7756 7949 1086  399]
 [   0    0    0    0    0 9092 7374 8916 4438 5808]
 [   0    0    0  993 8916 1086 7615 4526 8098 8419]]


In [8]:
length = 10
docs = pad_sequences(onehot_repre, padding='post', maxlen = length)

print(docs)

[[7756 7949 6485 9567    0    0    0    0    0    0]
 [7756 7949 1086 9834 2412  483    0    0    0    0]
 [7756   12 1323 8800    0    0    0    0    0    0]
 [7756 7949 1086  399    0    0    0    0    0    0]
 [9092 7374 8916 4438 5808    0    0    0    0    0]
 [ 993 8916 1086 7615 4526 8098 8419    0    0    0]]


In [9]:
dim = 0

In [10]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length= sent_length))
model.compile('adam', 'mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 10)            100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

1/1 [==============================] - 3s 3s/step
[[[-3.09899095e-02  3.76542844e-02 -1.99068431e-02  4.63854931e-02
    2.41295435e-02  7.17739016e-03  3.75283994e-02  1.47769339e-02
   -1.97736975e-02 -3.10777780e-02]
  [-3.09899095e-02  3.76542844e-02 -1.99068431e-02  4.63854931e-02
    2.41295435e-02  7.17739016e-03  3.75283994e-02  1.47769339e-02
   -1.97736975e-02 -3.10777780e-02]
  [-3.09899095e-02  3.76542844e-02 -1.99068431e-02  4.63854931e-02
    2.41295435e-02  7.17739016e-03  3.75283994e-02  1.47769339e-02
   -1.97736975e-02 -3.10777780e-02]
  [-3.09899095e-02  3.76542844e-02 -1.99068431e-02  4.63854931e-02
    2.41295435e-02  7.17739016e-03  3.75283994e-02  1.47769339e-02
   -1.97736975e-02 -3.10777780e-02]
  [-3.09899095e-02  3.76542844e-02 -1.99068431e-02  4.63854931e-02
    2.41295435e-02  7.17739016e-03  3.75283994e-02  1.47769339e-02
   -1.97736975e-02 -3.10777780e-02]
  [-3.09899095e-02  3.76542844e-02 -1.99068431e-02  4.63854931e-02
    2.41295435e-02  7.17739016e-0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0, 7756, 7949, 6485, 9567])

In [14]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 25ms/step
[[-0.03098991  0.03765428 -0.01990684  0.04638549  0.02412954  0.00717739
   0.0375284   0.01477693 -0.0197737  -0.03107778]
 [-0.03098991  0.03765428 -0.01990684  0.04638549  0.02412954  0.00717739
   0.0375284   0.01477693 -0.0197737  -0.03107778]
 [-0.03098991  0.03765428 -0.01990684  0.04638549  0.02412954  0.00717739
   0.0375284   0.01477693 -0.0197737  -0.03107778]
 [-0.03098991  0.03765428 -0.01990684  0.04638549  0.02412954  0.00717739
   0.0375284   0.01477693 -0.0197737  -0.03107778]
 [-0.03098991  0.03765428 -0.01990684  0.04638549  0.02412954  0.00717739
   0.0375284   0.01477693 -0.0197737  -0.03107778]
 [-0.03098991  0.03765428 -0.01990684  0.04638549  0.02412954  0.00717739
   0.0375284   0.01477693 -0.0197737  -0.03107778]
 [ 0.01853449 -0.04060259 -0.00139726 -0.03108188  0.01855961  0.02161228
  -0.04092807  0.0307742  -0.04203786 -0.03870223]
 [-0.0258092   0.00545164 -0.04470445 -0.04284167 -0.04696766 -0.03750009